services:
  mongo: 
    image: mongo:7.0
    container_name: silver_micro_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongadmin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db