version: '3.8'
services:
  mongo: 
    image: mongo:7.0
    container_name: container_silver_micro_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongadmin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - 27017:27017
    volumes:
      - ./silver_micro_db:/data/db